fig_wg1_spm1:
  variables:
      Surface Air Temperature Change|Median:
      Surface Air Temperature Change|Mean:
      Surface Air Temperature Change|5%:
      Surface Air Temperature Change|95%:
  annual_data: True
  raw_data_path: data/raw/dap.ceda.ac.uk/badc/ar6_wg1/data/spm/spm_01/v20210809
  output_data_path: data/processed/fig-spm1/fig-spm1-timeseries.csv
  compile_function: openscm_ar6_wg1_data_compilation.compile_spm_fig_1_timeseries
  comment: Data comes from a range of sources (observations, paleoclimate and CMIP6 models)

fig_wg1_spm4:
  variables:
      Emissions|CO2:
      Emissions|CH4:
      Emissions|N2O:
      Emissions|Sulfur:
  annual_data: True
  raw_data_path: data/raw/dap.ceda.ac.uk/badc/ar6_wg1/data/spm/spm_04/v20210809
  output_data_path: data/processed/fig-spm4/fig-spm4-timeseries.csv
  compile_function: openscm_ar6_wg1_data_compilation.compile_spm_fig_4_timeseries

fig_wg1_spm8:
  variables:
      Surface Air Temperature Change|Mean:
        comment: Comes from Ch. 4 assessment
      Surface Air Temperature Change|5%:
        comment: Comes from Ch. 4 assessment
      Surface Air Temperature Change|95%:
        comment: Comes from Ch. 4 assessment
      Ocean Surface pH|Mean:
      Ocean Surface pH|5%:
      Ocean Surface pH|95%:
      Arctic Sea Icea Area|September|Mean:
      Arctic Sea Icea Area|September|5%:
      Arctic Sea Icea Area|September|95%:
  annual_data: True
  raw_data_path: data/raw/dap.ceda.ac.uk/badc/ar6_wg1/data/spm/spm_08/v20210809
  output_data_path: data/processed/fig-spm8/fig-spm8-timeseries.csv
  compile_function: openscm_ar6_wg1_data_compilation.compile_spm_fig_8_timeseries

fig_wg1_spm10:
  variables:
      Surface Air Temperature Change|Mean:
        comment: Comes from Ch. 4 assessment (TODO check)
      Surface Air Temperature Change|5%:
        comment: Comes from Ch. 4 assessment (TODO check)
      Surface Air Temperature Change|95%:
        comment: Comes from Ch. 4 assessment (TODO check)
      Surface Air Temperature Change|Anthropogenic|Mean:
        comment: Comes from Ch. 2 assessment
      Surface Air Temperature Change|Anthropogenic|5%:
        comment: Comes from Ch. 2 assessment
      Surface Air Temperature Change|Anthropogenic|95%:
        comment: Comes from Ch. 2 assessment
      Cumulative Emissions|CO2:
  annual_data: True
  raw_data_path: data/raw/dap.ceda.ac.uk/badc/ar6_wg1/data/spm/spm_10/v20210809
  output_data_path: data/processed/fig-spm10/fig-spm10-timeseries.csv
  compile_function: openscm_ar6_wg1_data_compilation.compile_spm_fig_10_timeseries
